###############################################
# Redirect this crate to Vorot's implementation
###############################################

[package]
name = "mdbx-sys-proxy"
version = "0.0.0"
edition = "2021"

[lib]
name = "mdbx_sys_proxy"
path = "src/lib.rs"

[dependencies]
mdbx-sys = { package = "mdbx-sys", path = "../../vorots-repository/libmdbx-rs/mdbx-sys" }