[target.aarch64-linux-android]
rustflags = [
  "-C", "link-arg=-z",
  "-C", "link-arg=max-page-size=16384",
  "-C", "link-arg=-z",
  "-C", "link-arg=common-page-size=16384"
]
[target.armv7-linux-androideabi]
rustflags = [
  "-C", "link-arg=-z",
  "-C", "link-arg=max-page-size=16384",
  "-C", "link-arg=-z",
  "-C", "link-arg=common-page-size=16384"
]

[target.x86_64-linux-android]
rustflags = [
  "-C", "link-arg=-z",
  "-C", "link-arg=max-page-size=16384",
  "-C", "link-arg=-z",
  "-C", "link-arg=common-page-size=16384"
]

[target.i686-linux-android]
rustflags = [
  "-C", "link-arg=-z",
  "-C", "link-arg=max-page-size=16384",
  "-C", "link-arg=-z",
  "-C", "link-arg=common-page-size=16384"
]